import { referenceImage, aboutImage } from './reference-media';
import { desktop, NativeDisplay, nativeRequest } from './desktop/platform';
import { createExplorer, type ViewMode, type LightMode } from './scene';
import { CrosstalkClient } from '@crosstalk/client';
import { EuropaController } from './crosstalk/EuropaController';
import { EuropaFullscreen } from './crosstalk/EuropaFullscreen';
import { createEuropaCrosstalkAdapter } from './crosstalk/adapter';
import { buildingReference, sideBearings, type BuildingSide } from './spatial';

const icons: Record<string,string> = {
 arrow:'<path d="M7 17 17 7M7 7h10v10"/>', pin:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 cube:'<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Z M3 8l9 5 9-5M12 13v8M7.5 5.5l9 5"/>', plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',reset:'<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>', camera:'<path d="M4 6h4l2-3h4l2 3h4v14H4Z"/><circle cx="12" cy="12" r="4"/>', info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v1"/>', sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2M12 21v2M1 12h2M21 12h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',moon:'<path d="M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12Z"/>',play:'<path d="m9 5 11 7-11 7Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',mouse:'<rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v7"/>', layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>', sunset:'<path d="M3 17h18M5 21h14M7 17a5 5 0 0 1 10 0M12 2v4M3 8l3 3M21 8l-3 3"/>'
};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.cube}</svg>`;
const views=[{id:'urban',label:'Urban perspective',sub:'The building in its element',tag:'01'},{id:'street',label:'Street level',sub:'Look up. Take it all in.',tag:'02'},{id:'aerial',label:'Skyline view',sub:'A different point of view',tag:'03'}];
document.querySelector('#app')!.innerHTML=`
<header><a class="brand" href="/" aria-label="Europa home"><span class="brand-mark">${icon('cube')}</span>EUROPA<span class="brand-sub">ARCHITECTURAL EXPLORER</span></a><nav><span class="location">${icon('pin')} Valencia, Spain <span class="nav-divider"></span>${buildingReference.latitude.toFixed(6)}° N · ${Math.abs(buildingReference.longitude).toFixed(6)}° W</span><button class="about-button" id="about">About the building ${icon('arrow')}</button></nav></header>
<main><section class="intro"><div><div class="eyebrow"><span class="tiny-line"></span> VALENCIA, FROM A NEW PERSPECTIVE</div><h1>Edificio Europa<span>.</span></h1></div><p>A city landmark. Every angle.<br>Explore the architecture in three dimensions.</p></section>
<section class="viewer" aria-label="Interactive 3D architectural explorer"><div id="canvas-host"></div><div class="viewer-vignette"></div>
<div class="scene-label"><span class="live-dot"></span> INTERACTIVE 3D <span class="label-divider"></span><span id="scene-label">Urban perspective</span></div>
<section class="orientation" aria-label="Building orientation"><div class="orientation-current"><svg class="spatial-compass" viewBox="0 0 60 60" aria-hidden="true"><circle cx="30" cy="30" r="20" fill="none" stroke="currentColor" opacity=".25"/><text x="30" y="8" text-anchor="middle">N</text><text x="55" y="33" text-anchor="middle">E</text><text x="30" y="59" text-anchor="middle">S</text><text x="5" y="33" text-anchor="middle">W</text><g transform="rotate(10 30 30)"><rect x="25" y="20" width="10" height="20" rx="2" fill="currentColor" opacity=".25"/><path d="M25 20h10" stroke="currentColor" stroke-width="3"/></g><g id="camera-bearing"><circle cx="30" cy="12" r="3.5" fill="currentColor"/></g></svg><div><small>VIEWING FROM</small><strong id="orientation-label">Locating camera…</strong><span>Entrance faces N 10° E</span></div></div><div class="side-controls" aria-label="View a building side">${Object.keys(sideBearings).map(side=>`<button data-side="${side}" aria-label="Show ${side} of building" aria-pressed="false">${side[0]!.toUpperCase()+side.slice(1)}</button>`).join('')}</div><p>Left / right as you face the entrance</p></section>
<div class="viewer-top-right"><span class="quality">HIGH RESOLUTION</span><button class="round light-button" id="info" aria-label="Navigation help">${icon('info')}</button></div>
<div class="scene-title"><span id="scene-number">01 / 03</span><h2 id="view-title">The urban perspective.</h2><p id="view-description">Glass, stone, and a Mediterranean skyline.</p></div>
<aside class="perspectives"><div class="panel-heading"><span>CHOOSE YOUR PERSPECTIVE</span>${icon('layers')}</div>${views.map(v=>`<button class="view-card ${v.id==='urban'?'active':''}" data-view="${v.id}" aria-pressed="${v.id==='urban'}"><div class="view-photo">${desktop?icon('cube'):referenceImage(Number(v.tag)-1,v.label)}<span>${v.tag}</span></div><div class="view-card-text"><strong>${v.label}</strong><small>${v.sub}</small></div><span class="selected-indicator">${v.id==='urban'?icon('chevron'):''}</span></button>`).join('')}<div class="panel-note">Three viewpoints. Infinite ways to explore.</div></aside>
<div class="bottom-bar"><div class="lighting"><span class="control-label">LIGHT</span><button data-light="day" class="active" aria-pressed="true">${icon('sun')}<span>Daylight</span></button><button data-light="golden" aria-pressed="false">${icon('sunset')}<span>Golden hour</span></button><button data-light="blue" aria-pressed="false">${icon('moon')}<span>Blue hour</span></button></div><div class="navigation-tip">${icon('mouse')} Drag to orbit <span>·</span> Scroll to zoom</div><div class="camera-controls"><button id="rotate" title="Auto-rotate" aria-label="Auto-rotate" aria-pressed="false">${icon('play')}</button><span class="tool-divider"></span><button id="zoom-in" aria-label="Zoom in">${icon('plus')}</button><button id="zoom-out" aria-label="Zoom out">${icon('minus')}</button><button id="reset" aria-label="Reset view">${icon('reset')}</button><span class="tool-divider"></span><button id="capture" aria-label="Download 4K image" title="Download 4K image">${icon('camera')}</button><button id="fullscreen" aria-label="Toggle fullscreen">${icon('expand')}</button></div></div>
<div id="loading"><span class="loading-spinner"></span><strong>Bringing Europa into perspective</strong><span>Preparing your 3D experience</span></div><div id="toast" role="status"></div>
</section><footer><span>${icon('cube')} Built to be explored.<span class="footer-divider">/</span> A photo-based architectural study</span><a href="https://maps.app.goo.gl/gQwHSTFF8XgvJrEu8" target="_blank" rel="noopener noreferrer">Find it in Valencia ${icon('arrow')}</a></footer></main>
<dialog id="about-dialog"><button class="dialog-close" aria-label="Close">${icon('close')}</button><div class="eyebrow">THE ARCHITECTURAL STUDY</div><h2>A landmark in reflection.</h2>${aboutImage()}<p>Edificio Europa stands in Valencia, Spain. Its dark vertical stone ribs, reflective glass façade, and cylindrical corner entrance give the building its distinctive silhouette.</p><p>This interactive reconstruction is based on the supplied photographs. Geometry, scale, landscaping, and neighboring buildings are interpretive, rather than a measured architectural survey.</p><a href="https://maps.app.goo.gl/gQwHSTFF8XgvJrEu8" target="_blank" rel="noopener noreferrer">View the location ${icon('arrow')}</a></dialog>
<dialog id="help-dialog"><button class="dialog-close" aria-label="Close">${icon('close')}</button><div class="eyebrow">MAKE IT YOUR PERSPECTIVE</div><h2>Around. Above. Up close.</h2><dl><dt>Orbit the building</dt><dd>Click and drag, or swipe with one finger.</dd><dt>Zoom in and out</dt><dd>Scroll, pinch with two fingers, or use + and −.</dd><dt>Pan the scene</dt><dd>Right-click and drag, or drag with two fingers.</dd><dt>Keyboard navigation</dt><dd>Arrow keys pan. + and − zoom. R resets the view.</dd><dt>Keep a perspective</dt><dd>The camera button downloads a 3840 × 2160 PNG.</dd></dl></dialog>`;
if(desktop){document.documentElement.classList.add('desktop');document.querySelectorAll<HTMLAnchorElement>('a[target="_blank"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();void nativeRequest('location',{id:'building-location'}).catch(()=>{});}));document.querySelector('#capture')!.setAttribute('aria-label','Save 4K image');}
const toast=(message:string)=>{const el=document.querySelector('#toast')!;el.textContent=message;el.classList.add('visible');window.setTimeout(()=>el.classList.remove('visible'),3500)};
const bind=(id:string,fn:()=>void)=>document.getElementById(id)!.addEventListener('click',fn);
for(const [id,dialogId] of [['about','about-dialog'],['info','help-dialog']]) bind(id!,()=>{(document.getElementById(dialogId!) as HTMLDialogElement).showModal()});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('button')!.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()})});
try {
 const explorer=createExplorer(document.querySelector('#canvas-host')!);
 const titles={urban:['The urban perspective.','Glass, stone, and a Mediterranean skyline.'],street:['A closer kind of wonder.','Follow the reflections from the street to the sky.'],aerial:['Above the everyday.','Discover Europa’s place in the fabric of Valencia.']};
 const controller=new EuropaController(explorer,state=>{
  document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>{const active=b.dataset.view===state.perspective&&!state.viewAdjusted&&!state.autoRotate;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));b.querySelector('.selected-indicator')!.innerHTML=active?icon('chevron'):''});
  document.querySelector('#view-title')!.textContent=titles[state.perspective][0]!;document.querySelector('#view-description')!.textContent=titles[state.perspective][1]!;
  document.querySelector('#scene-label')!.textContent=views.find(v=>v.id===state.perspective)!.label;document.querySelector('#scene-number')!.textContent=`0${views.findIndex(v=>v.id===state.perspective)+1} / 03`;
  document.querySelectorAll<HTMLButtonElement>('[data-light]').forEach(b=>{const active=b.dataset.light===state.lighting;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
  document.querySelector('#rotate')!.innerHTML=icon(state.autoRotate?'pause':'play');document.querySelector('#rotate')!.setAttribute('aria-pressed',String(state.autoRotate));
  const spatial=state.spatial;
  if(spatial){
   const side=spatial.cameraSide.replaceAll('-',' ');const label=side[0]!.toUpperCase()+side.slice(1);
   document.querySelector('#orientation-label')!.textContent=`${label}${spatial.cameraCompass?` · ${spatial.cameraCompass} ${Math.round(spatial.cameraBearingDegrees!)%360}°`:''}`;
   document.querySelector('#camera-bearing')!.setAttribute('transform',`rotate(${spatial.cameraBearingDegrees??0} 30 30)`);
   document.querySelector('#camera-bearing')!.setAttribute('visibility',spatial.cameraBearingDegrees===null?'hidden':'visible');
   if(state.viewAdjusted||state.autoRotate){document.querySelector('#view-title')!.textContent=`${label} view.`;document.querySelector('#view-description')!.textContent=state.transitioning?'Moving around the building…':'The entrance is the front. Explore every side.';document.querySelector('#scene-label')!.textContent=state.autoRotate?'Orbiting':`${label} view`;document.querySelector('#scene-number')!.textContent='EXPLORE / EUROPA';}
  }
  document.querySelectorAll<HTMLButtonElement>('[data-side]').forEach(b=>b.setAttribute('aria-pressed',String(!state.transitioning&&spatial?.cameraSide===b.dataset.side)));
  const fullscreen=document.querySelector<HTMLButtonElement>('#fullscreen')!;fullscreen.setAttribute('aria-pressed',String(state.fullscreen));fullscreen.setAttribute('aria-label',state.fullscreen?'Exit fullscreen':'Enter fullscreen');fullscreen.title=state.fullscreen?'Exit fullscreen':'Enter fullscreen';
 },desktop?new NativeDisplay():new EuropaFullscreen(document.querySelector<HTMLElement>('.viewer')!,toast));
 const navigate=(action:Promise<void>)=>{void action.catch(error=>{if(!(error instanceof Error)||error.name!=='AbortError')toast('This perspective is unavailable. Please try again.');});};
 document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button=>button.addEventListener('click',()=>navigate(controller.setPerspective(button.dataset.view as ViewMode))));
 document.querySelectorAll<HTMLButtonElement>('[data-light]').forEach(button=>button.addEventListener('click',()=>controller.setLighting(button.dataset.light as LightMode)));
 document.querySelectorAll<HTMLButtonElement>('[data-side]').forEach(button=>button.addEventListener('click',()=>navigate(controller.showSide(button.dataset.side as BuildingSide))));
 bind('rotate',()=>controller.setAutoRotate(!controller.getState().autoRotate));
 bind('reset',()=>navigate(controller.resetPerspective()));bind('zoom-in',()=>controller.adjustZoom('closer'));bind('zoom-out',()=>controller.adjustZoom('farther'));
 bind('capture',()=>{void controller.capture().then(()=>toast(desktop?'Your 4K perspective was saved':'Your 4K perspective is ready')).catch(error=>toast(error instanceof Error?error.message:'Image export was unavailable.'));});
 const crosstalk=new CrosstalkClient({endpoint:'/crosstalk',...(desktop?{desktopWorklet:'/audio-worklet.js'}:{})});
 crosstalk.mountButton({position:'bottom-right'});
 void crosstalk.register(createEuropaCrosstalkAdapter(controller,desktop)).catch(()=>toast('Voice is reconnecting. The explorer is ready to use.'));
 window.addEventListener('pagehide',()=>crosstalk.dispose(),{once:true});
 bind('fullscreen',()=>{void controller.setFullscreen(!controller.getState().fullscreen).catch(()=>{if(desktop)toast('The window could not change fullscreen mode. Please try again.');});});
 document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.composedPath().some(el=>el instanceof HTMLElement&&(el.isContentEditable||['INPUT','TEXTAREA'].includes(el.tagName))))return;if(e.key==='+'||e.key==='=')controller.adjustZoom('closer','small');if(e.key==='-')controller.adjustZoom('farther','small');if(e.key.toLowerCase()==='r')navigate(controller.resetPerspective())});
 requestAnimationFrame(()=>{controller.setReady(true);document.querySelector('#loading')!.classList.add('loaded');});
} catch(error){console.error(error);document.querySelector('#loading')!.innerHTML='<strong>Your browser could not start the 3D view.</strong><span>Enable hardware acceleration or try a WebGL-capable browser.</span>';}
