import type { CrosstalkApplication, CrosstalkTool, CrosstalkToolDefinition, CrosstalkToolContext } from '../../cross-talk/src/protocol';
import { CrosstalkError } from '../../cross-talk/src/protocol';
import { europaManifest, type EuropaState } from './manifest';
import type { EuropaController } from './EuropaController';
import { sideBearings, compassBearings } from '../spatial';
const input = (properties: Record<string, unknown>, required = Object.keys(properties)) => ({ type: 'object', properties, required, additionalProperties: false });
export function createEuropaCrosstalkAdapter(controller: EuropaController, native = false): CrosstalkApplication<EuropaState> {
  const tool = (definition: Omit<CrosstalkToolDefinition, 'effect' | 'confirmation' | 'interruptible'> & Partial<CrosstalkToolDefinition>, execute: (args: any, context: CrosstalkToolContext) => unknown): CrosstalkTool => ({
    definition: { effect: 'navigation', confirmation: 'never', interruptible: false, ...definition },
    execute(args, context) {
      context.signal.throwIfAborted();
      if (!controller.getState().ready) throw new CrosstalkError('APPLICATION_NOT_READY', 'The 3D explorer is still loading.', true);
      return execute(args, context);
    },
  });
  const manifest = native ? { ...europaManifest, domain: { ...europaManifest.domain, limitations: europaManifest.domain.limitations.filter(text => !text.startsWith('Entering fullscreen')).concat('Fullscreen changes the native OS window and is reported only after the window state settles. Saving a PNG opens a native save dialog; cancellation does not save a file.') } } : europaManifest;
  return { manifest, getState: controller.getState, subscribe: controller.subscribe, tools: [
    tool({ name: 'show_side', title: 'Show a building or compass side', description: 'Move around the building to view the front (entrance, 010°), back (opposite end, 190°), left (100°) or right (280°). Left/right are fixed as seen facing the entrance from outside. Compass names place the camera on that geographic side looking toward the building; north means viewing FROM north, not looking north. Stops auto-rotation, recenters, and follows an exterior arc. Resolves after settling.', inputSchema: input({ side: { type: 'string', enum: [...Object.keys(sideBearings), ...Object.keys(compassBearings)] } }), interruptible: true, expectedDurationMs: 1400 }, async ({ side }, context) => { await controller.showSide(side, context.signal); return { spatial: controller.getState().spatial, settled: true }; }),
    tool({ name: 'orbit_view', title: 'Orbit from the current viewpoint', description: 'Move the camera to the viewer’s left or right around the building, keeping the building centered. This is relative camera movement, not selection of a fixed building side, panning, or spinning the model. Default 30 degrees; use 15 for a little and 180 for the opposite side. Stops auto-rotation. Resolves after settling.', inputSchema: input({ direction: { type: 'string', enum: ['left', 'right'] }, degrees: { type: 'number', minimum: 1, maximum: 180 } }, ['direction']), interruptible: true, expectedDurationMs: 1400 }, async ({ direction, degrees }, context) => { await controller.orbitView(direction, degrees, context.signal); return { spatial: controller.getState().spatial, settled: true }; }),
    tool({ name: 'set_fullscreen', title: 'Change fullscreen mode', description: native ? 'Enter or exit the native window fullscreen mode. State reflects the OS window; no browser activation is needed.' : 'Enter fullscreen (enabled true) or return to normal view (enabled false). This changes display mode, not the camera perspective. Entry may require a recent user click; if blocked, ask the user to click the fullscreen button.', inputSchema: input({ enabled: { type: 'boolean' } }) }, async ({ enabled }) => { await controller.setFullscreen(enabled); return { fullscreen: controller.getState().fullscreen }; }),
    tool({ name: 'show_perspective', title: 'Show architectural perspective', description: 'Move to urban (wide surroundings), street (entrance) or aerial (roof) view. Use for a new angle or to guide exploration. Resolves after the camera settles.', inputSchema: input({ perspective: { type: 'string', enum: ['urban', 'street', 'aerial'] } }), interruptible: true, expectedDurationMs: 1400 }, async ({ perspective }, context) => { await controller.setPerspective(perspective, context.signal); return { perspective, settled: true }; }),
    tool({ name: 'set_lighting', title: 'Change environmental lighting', description: 'Change simulated time of day: day for daylight, golden for sunset, blue for blue hour or dusk.', inputSchema: input({ lighting: { type: 'string', enum: ['day', 'golden', 'blue'] } }) }, ({ lighting }) => { controller.setLighting(lighting); return { lighting }; }),
    tool({ name: 'set_auto_rotation', title: 'Control automatic rotation', description: 'Start or stop the slow automatic orbit around the building.', inputSchema: input({ enabled: { type: 'boolean' } }) }, ({ enabled }) => { controller.setAutoRotate(enabled); return { autoRotate: enabled }; }),
    tool({ name: 'adjust_zoom', title: 'Adjust view distance', description: 'Move closer to or farther from the current focus. The default amount is medium.', inputSchema: input({ direction: { type: 'string', enum: ['closer', 'farther'] }, amount: { type: 'string', enum: ['small', 'medium', 'large'] } }, ['direction']) }, ({ direction, amount }) => { controller.adjustZoom(direction, amount); return { zoomLevel: controller.getState().zoomLevel }; }),
    tool({ name: 'reset_view', title: 'Reset current perspective', description: 'Return the camera to its currently selected predefined perspective without changing lighting.', inputSchema: input({}), interruptible: true, expectedDurationMs: 1400 }, async (_, context) => { await controller.resetPerspective(context.signal); return { perspective: controller.getState().perspective, settled: true }; }),
    tool({ name: 'capture_view', title: 'Save current architectural view', description: 'Download the visible perspective as a 3840 × 2160 PNG. Only execute for a direct save request or after confirmation; a question about saving does not request a download.', inputSchema: input({}), effect: 'external', confirmation: 'when-not-explicit', interruptible: native }, (_, context) => controller.capture(context.invocationId, context.signal)),
  ] };
}
